if(UNIX)
    find_package(Qt5 COMPONENTS Core Widgets QUIET)
elseif(WIN32)
    if(Qt5_DIR)
        find_package(Qt5 COMPONENTS Core Widgets QUIET)
    else()
        # e.g. see https://blog.kitware.com/cmake-finding-qt5-the-right-way/
        message(STATUS "On Windows in order to find Qt you have to set 'Qt5_DIR' to the path containing the Qt5Config.cmake before running CMake! Otherwise the Qt installation can not be located.")
    endif()
endif()
if(Qt5Widgets_FOUND)
    message(STATUS "Qt found here: ${Qt5Widgets_DIR}!")
else()
    message(STATUS "Qt applications will not be compiled as no compatible Qt version could be detected!")
endif()