/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_acquire_WRAP_H_
#define SWIG_acquire_WRAP_H_

#include <map>
#include <string>


class SwigDirector_ComponentCallback : public mvIMPACT::acquire::ComponentCallback, public Swig::Director {

public:
    SwigDirector_ComponentCallback(PyObject *self, void *pUserData = 0);
    SwigDirector_ComponentCallback(PyObject *self, mvIMPACT::acquire::ComponentCallback const &src);
    virtual ~SwigDirector_ComponentCallback();
    virtual void execute(mvIMPACT::acquire::Component &c, void *pUserData);

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class ComponentCallback doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[1];
#endif

};


class SwigDirector_Request : public mvIMPACT::acquire::Request, public Swig::Director {

public:
    SwigDirector_Request(PyObject *self, mvIMPACT::acquire::Device *pDev, int requestNr);
    SwigDirector_Request(PyObject *self, mvIMPACT::acquire::Request const &src);
    virtual ~SwigDirector_Request();

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;
};


class SwigDirector_RequestFactory : public mvIMPACT::acquire::RequestFactory, public Swig::Director {

public:
    SwigDirector_RequestFactory(PyObject *self);
    virtual ~SwigDirector_RequestFactory();
    virtual mvIMPACT::acquire::Request *createRequest(mvIMPACT::acquire::Device *arg0, int arg1);

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class RequestFactory doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[1];
#endif

};


class SwigDirector_FirmwareUpdater : public mvIMPACT::acquire::labs::FirmwareUpdater, public Swig::Director {

public:
    SwigDirector_FirmwareUpdater(PyObject *self, mvIMPACT::acquire::Device *pDev, bool boForceOverideSameVersion = false, bool boForceDowngrade = false, bool boKeepUserSets = true, bool boForceBreakingChange = false);
    virtual ~SwigDirector_FirmwareUpdater();
    virtual int onErrorMessage(double const arg0) const;
    virtual int onErasingFlash(int const arg0, double const arg1) const;
    virtual int onUnzippingFirmwareArchive(int const arg0, double const arg1) const;
    virtual int onUpdatingBootProgrammer(int const arg0, double const arg1) const;
    virtual int onUploadingImage(int const arg0, double const arg1) const;
    virtual int onRebooting(int const arg0, double const arg1) const;
    virtual int onSavingUserSets(int const arg0, double const arg1) const;
    virtual int onLoadingUserSets(int const arg0, double const arg1) const;
    using mvIMPACT::acquire::labs::FirmwareUpdater::setTimeElapsed;

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class FirmwareUpdater doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[8];
#endif

};


#endif
